package com.yem.hlm.backend.tls;

import com.yem.hlm.backend.support.IntegrationTestBase;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManagerBuilder;
import org.apache.hc.client5.http.ssl.NoopHostnameVerifier;
import org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.*;
import org.springframework.http.client.ClientHttpResponse;
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory;
import org.springframework.test.context.TestPropertySource;
import org.springframework.web.client.ResponseErrorHandler;
import org.springframework.web.client.RestTemplate;

import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.cert.X509Certificate;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.boot.test.context.SpringBootTest.WebEnvironment.RANDOM_PORT;

/**
 * Integration test verifying that TLS/HTTPS is correctly configured.
 *
 * <p>Starts the full Spring Boot application on a random HTTPS port using the
 * test keystore generated by the Maven exec plugin during generate-test-resources.
 *
 * <p>Tests HSTS header presence (only emitted when server.ssl.enabled=true).
 */
@SpringBootTest(webEnvironment = RANDOM_PORT)
@TestPropertySource(properties = {
        "server.ssl.enabled=true",
        "server.ssl.key-store=classpath:ssl/hlm-dev.p12",
        "server.ssl.key-store-password=changeit",
        "server.ssl.key-alias=hlm-dev",
        "server.ssl.key-store-type=PKCS12",
        "management.health.defaults.enabled=false",
        "management.health.ping.enabled=true"
})
class TlsConfigIT extends IntegrationTestBase {

    @LocalServerPort
    int port;

    private RestTemplate restTemplate;

    @BeforeEach
    void setUp() throws Exception {
        // Trust all certificates for testing (self-signed dev cert)
        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, new TrustManager[]{new X509TrustManager() {
            public X509Certificate[] getAcceptedIssuers() { return new X509Certificate[0]; }
            public void checkClientTrusted(X509Certificate[] chain, String authType) {}
            public void checkServerTrusted(X509Certificate[] chain, String authType) {}
        }}, null);

        SSLConnectionSocketFactory sslSocketFactory = new SSLConnectionSocketFactory(
                sslContext, NoopHostnameVerifier.INSTANCE);

        CloseableHttpClient httpClient = HttpClients.custom()
                .setConnectionManager(
                        PoolingHttpClientConnectionManagerBuilder.create()
                                .setSSLSocketFactory(sslSocketFactory)
                                .build())
                .build();

        restTemplate = new RestTemplate(new HttpComponentsClientHttpRequestFactory(httpClient));
        // Never throw on 4xx/5xx — return the ResponseEntity so tests can assert on status codes
        restTemplate.setErrorHandler(new ResponseErrorHandler() {
            @Override public boolean hasError(ClientHttpResponse r) { return false; }
            @Override public void handleError(ClientHttpResponse r) {}
        });
    }

    @Test
    void health_over_https_returns_200() {
        String url = "https://localhost:" + port + "/actuator/health";
        ResponseEntity<String> resp = restTemplate.getForEntity(url, String.class);
        assertThat(resp.getStatusCode()).isEqualTo(HttpStatus.OK);
    }

    @Test
    void login_over_https_returns_401_for_invalid_creds() {
        String url = "https://localhost:" + port + "/auth/login";
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<String> req = new HttpEntity<>(
                "{\"email\":\"x@x.com\",\"password\":\"wrong\"}", headers);
        ResponseEntity<String> resp = restTemplate.exchange(url, HttpMethod.POST, req, String.class);
        assertThat(resp.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }

    @Test
    void hsts_header_is_present() {
        String url = "https://localhost:" + port + "/actuator/health";
        ResponseEntity<String> resp = restTemplate.getForEntity(url, String.class);
        assertThat(resp.getHeaders().getFirst("Strict-Transport-Security"))
                .contains("max-age=31536000");
    }
}
