spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yem_dev
    username: yem
    password: yem
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info