package com.yem.hlm.backend.vente.domain;

/**
 * Categorises a {@link VenteDocument}.
 *
 * <ul>
 *   <li>{@code CONTRAT_GENERE} – contract generated by the agent (staff upload)</li>
 *   <li>{@code CONTRAT_SIGNE_CLIENT} – signed copy returned by the buyer via the portal</li>
 *   <li>{@code CONTRAT_SIGNE_FINAL} – countersigned final copy confirmed by the agent</li>
 *   <li>{@code PV_RECEPTION} – procès-verbal de réception (post-delivery acceptance document)</li>
 *   <li>{@code AUTRE} – any other document</li>
 * </ul>
 */
public enum VenteDocumentType {
    CONTRAT_GENERE,
    CONTRAT_SIGNE_CLIENT,
    CONTRAT_SIGNE_FINAL,
    PV_RECEPTION,
    AUTRE
}
